language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install coveralls
# command to run tests
script: nosetests --with-coverage
after_success:
  coveralls